// Auto-generated by build_traffic_data.mjs
import type { DateTrafficData, SitePhoto } from '../app/types';
import _datesConfig       from './dates-config.json';
import _segmentsGeo       from './segments-geo.json';
import _sitePhotosMountMary from './site-visit-mount-mary.json';
import _sep_07_2025 from './traffic-sep-07-2025.json';
import _sep_13_2025 from './traffic-sep-13-2025.json';
import _sep_01_2024 from './traffic-sep-01-2024.json';
import _sep_07_2024 from './traffic-sep-07-2024.json';
import _sep_14_2025 from './traffic-sep-14-2025.json';
import _sep_20_2025 from './traffic-sep-20-2025.json';
import _sep_08_2024 from './traffic-sep-08-2024.json';
import _sep_14_2024 from './traffic-sep-14-2024.json';

export const datesConfig   = _datesConfig;
export const segmentsGeo   = _segmentsGeo;
export const sitePhotosMountMary = _sitePhotosMountMary as SitePhoto[];

export const ALL_DATES_DATA: Record<string, DateTrafficData> = {
  'sep-07-2025': _sep_07_2025 as DateTrafficData,
  'sep-13-2025': _sep_13_2025 as DateTrafficData,
  'sep-01-2024': _sep_01_2024 as DateTrafficData,
  'sep-07-2024': _sep_07_2024 as DateTrafficData,
  'sep-14-2025': _sep_14_2025 as DateTrafficData,
  'sep-20-2025': _sep_20_2025 as DateTrafficData,
  'sep-08-2024': _sep_08_2024 as DateTrafficData,
  'sep-14-2024': _sep_14_2024 as DateTrafficData,
};
